apiVersion: apps/v1
kind: Deployment
metadata:
  name: gbv-replybot
  labels:
    app: gbv-replybot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gbv-replybot
  template:
    metadata:
      labels:
        app: gbv-replybot
    spec:
      containers:
      - name: gbv-replybot
        image: localhost:5000/replybot:registry
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "50m"
            memory: "100Mi"
        envFrom:
        - secretRef:
            name: gbv-bot-envs
        env:
        - name: CHATBASE_BACKEND
          value: "@vlab-research/chatbase-postgres"
        - name: CHATBASE_DATABASE
          value: "chatroach"
        - name: CHATBASE_USER
          value: "chatroach"
        - name: CHATBASE_PASSWORD
          value: ""
        - name: CHATBASE_HOST
          value: "gbv-cockroachdb-public.default"
        - name: CHATBASE_PORT
          value: "26257"
        - name: FALLBACK_FORM
          value: "305"
        - name: REPLYBOT_EVENT_TOPIC
          value: "chat-events"
        - name: FACEBOOK_GRAPH_URL
          value: "http://gbv-facebot"
        - name: BOTSPINE_KAFKA_BROKERS
          value: "gbv-kafka:9092"
        - name: KAFKA_BROKERS
          value: "gbv-kafka:9092"
        - name: BOTSPINE_MESSAGE_TOPIC
          value: "chat-events"
        - name: VLAB_STATE_TOPIC
          value: "vlab-state"
        - name: VLAB_RESPONSE_TOPIC
          value: "vlab-response"
        - name: DASHBOARD_API
          value: "http://gbv-dashboard/api/v1"
        - name: BOTSERVER_URL
          value: "http://gbv-botserver"
