version: '3'
services:
  botserver:
    build: .
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules/
    env_file: .env
    ports:
      - "3000:80"
  replybot:
    image: nandanrao/gbv-replybot
    env_file: .env
  redis:
    image: redis
