replicas: 1

imageTag: 5.1.2

kafkaHeapOptions: "-Xmx250m -Xms50m"

configurationOverrides:
  "offsets.topic.replication.factor": 1

topics:
  - name: chat-events
    partitions: 2
    replicationFactor: 1
