[context.production.environment]
REACT_APP_SERVER_URL="https://gbv-dashboard.nandan.cloud"
REACT_APP_TYPEFORM_REDIRECT_URL="https://vlab-research.netlify.app/surveys/auth"
REACT_APP_AUTH0_CALLBACK_URL="https://vlab-research.netlify.app/auth"

[context.staging.environment]
REACT_APP_SERVER_URL="https://gbv-dashboard-staging.nandan.cloud"
REACT_APP_TYPEFORM_REDIRECT_URL="https://staging--vlab-research.netlify.app/surveys/auth"
REACT_APP_AUTH0_CALLBACK_URL="https://staging--vlab-research.netlify.app/auth"
