image:
  repository: localhost:5000/dean
  tag: registry
  pullPolicy: Always

env:
- name: CHATBASE_DATABASE
  value: "chatroach"
- name: CHATBASE_USER
  value: "chatroach"
- name: CHATBASE_PASSWORD
  value: ""
- name: CHATBASE_HOST
  value: "gbv-cockroachdb-public"
- name: CHATBASE_PORT
  value: "26257"
- name: BOTSERVER_URL
  value: "http://gbv-botserver/synthetic"
- name: DEAN_FB_CODES
  value: "2022,-1"
- name: DEAN_BLOCKED_INTERVAL
  value: "24 hours"
- name: DEAN_RESPONDING_INTERVAL
  value: "23 hours"
- name: DEAN_RESPONDING_GRACE
  value: "1 hour"

queries:
  # - name: respondings
  #   queries: "respondings,blocked"
  #   schedule: "*/1 * * * *"
  #   resources:
  #     requests:
  #       cpu: 10m
  #       memory: 10Mi

  - name: timeouts
    queries: "timeouts"
    schedule: "*/1 * * * *"
    resources:
      requests:
        cpu: 10m
        memory: 10Mi
