image:
  repository: vlabresearch/redobot
  tag: 0.0.6
  pullPolicy: IfNotPresent

schedule: "0 20 * * *"
resources:
  requests:
    cpu: 20m
    memory: 64Mi
env:
- name: CHATBASE_DATABASE
  value: "chatroach"
- name: CHATBASE_USER
  value: "chatroach"
- name: CHATBASE_PASSWORD
  value: ""
- name: CHATBASE_HOST
  value: "gbv-cockroachdb-public"
- name: CHATBASE_PORT
  value: "26257"
- name: BOTSERVER_URL
  value: "http://gbv-botserver/synthetic"
- name: REDO_FB_CODES
  value: "2022,-1"
- name: REDO_BLOCKED_INTERVAL
  value: "24 hour"
- name: REDO_RESPONDING_INTERVAL
  value: "30 days"
