apiVersion: apps/v1
kind: Deployment
metadata:
  name: gbv-facebot
  labels:
    app: gbv-facebot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gbv-facebot
  template:
    metadata:
      labels:
        app: gbv-facebot
    spec:
      containers:
      - name: gbv-facebot
        image: localhost:32000/facebot:registry
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "50m"
            memory: "100Mi"
        ports:
        - containerPort: 3000
        - containerPort: 4000
        envFrom:
        - secretRef:
            name: gbv-bot-envs
        env:
        - name: KAFKA_BROKERS
          value: "spinaltap-kafka:9092"
