apiVersion: apps/v1
kind: Deployment
metadata:
  name: gbv-replybot
  labels:
    app: gbv-replybot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gbv-replybot
  template:
    metadata:
      labels:
        app: gbv-replybot
    spec:
      containers:
      - name: gbv-replybot
        image: nandanrao/gbv-replybot:0.0.5
        resources:
          requests:
            cpu: "50m"
            memory: "100Mi"
        ports:
        - containerPort: 80
        volumeMounts:
          - name: keys
            mountPath: /usr/src/app/keys
            readOnly: true
        envFrom:
        - secretRef:
            name: gbv-bot-envs
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: "keys/key.json"
      volumes:
        - name: keys
          secret:
            secretName: gbv-replybot-keys
