apiVersion: apps/v1
kind: Deployment
metadata:
  name: gbv-botserver
  labels:
    app: gbv-botserver
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gbv-botserver
  template:
    metadata:
      labels:
        app: gbv-botserver
    spec:
      containers:
      - name: gbv-botserver
        image: nandanrao/gbv-botserver:0.0.2
        resources:
          requests:
            cpu: "100m"
            memory: "500Mi"
        ports:
        - containerPort: 80
        envFrom:
        - secretRef:
            name: gbv-bot-envs

