apiVersion: batch/v1
kind: Job
metadata:
  name: gbv-testrunner
  labels:
    app: gbv-testrunner
spec:
  template:
    metadata:
      labels:
        app: gbv-testrunner
    spec:
      restartPolicy: "Never"
      containers:
      - name: gbv-testrunner
        image: localhost:32000/testrunner:registry
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "50m"
            memory: "100Mi"
        ports:
        - containerPort: 88
        envFrom:
        - secretRef:
            name: gbv-bot-envs
        env:
        - name: BOTSERVER_URL
          value: "http://gbv-botserver"
        - name: KAFKA_BROKERS
          value: "spinaltap-kafka:9092"
        - name: CHATBASE_BACKEND
          value: "@vlab-research/chatbase-postgres"
        - name: CHATBASE_DATABASE
          value: "chatroach"
        - name: CHATBASE_USER
          value: "chatroach"
        - name: CHATBASE_PASSWORD
          value: ""
        - name: CHATBASE_HOST
          value: "chatroach-cockroachdb-public.default"
        - name: CHATBASE_PORT
          value: "26257"
