# tied to single kafka release...
kafkaExporter:
  kafka:
    servers:
      - kafka-headless:29092

image:
  repository: danielqsj/kafka-exporter
  tag: latest
  pullPolicy: Always

prometheus:
  serviceMonitor: 
    enabled: true
