version: '3'
services:
  replybot:
    image: nandanrao/gbv-replybot
    volumes:
      - ./server:/usr/src/app/server
    env_file: .env
    command: npm run dev
  botserver:
    image: nandanrao/gbv-botserver
    volumes:
      - ../botserver/server:/usr/src/app/server
    env_file: .env
    ports:
      - "3000:80"
  redis:
    image: redis
