apiVersion: v1
entries:
  botscribe:
  - apiVersion: v2
    created: "2021-09-13T20:27:11.707839387+02:00"
    description: A Helm chart for Kubernetes
    digest: a1dd0f8199fb4121bcc66ded73ae560118c4568e9141ac9aa57d7306d7834cb8
    name: botscribe
    type: application
    urls:
    - botscribe-0.0.1.tgz
    version: 0.0.1
  botserver:
  - apiVersion: v2
    created: "2021-09-13T20:27:11.708540938+02:00"
    description: A Helm chart for Kubernetes
    digest: 585e8eebb456f0a8cfc5fe266c6512f36350d8d2cf5e2c76dca49ec813d81f0b
    name: botserver
    type: application
    urls:
    - botserver-0.0.1.tgz
    version: 0.0.1
  dashboard:
  - apiVersion: v2
    created: "2021-09-13T20:27:11.709048095+02:00"
    description: A Helm chart for Kubernetes
    digest: edec85b5f5b67496bf09eca15a575f4d57e215ae7e7bbdd19114e1e2ebbd8e1d
    name: dashboard
    type: application
    urls:
    - dashboard-0.0.1.tgz
    version: 0.0.1
  dean:
  - apiVersion: v2
    created: "2021-09-13T20:27:11.709574047+02:00"
    description: A Helm chart for Kubernetes
    digest: d810f51871138b070920bf7bab4ee54bcfa2f7f4cbef82e013c8a87be1eca522
    name: dean
    type: application
    urls:
    - dean-0.0.2.tgz
    version: 0.0.2
  - apiVersion: v2
    created: "2021-09-13T20:27:11.709400369+02:00"
    description: A Helm chart for Kubernetes
    digest: a2a40eb659f884e02232aa1f4250adb807800c2648de747416108e494850d6b9
    name: dean
    type: application
    urls:
    - dean-0.0.1.tgz
    version: 0.0.1
  dinersclub:
  - apiVersion: v2
    created: "2021-09-13T20:27:11.709905361+02:00"
    description: A Helm chart for Kubernetes
    digest: a246b3d53a1440536a8135785decb2b392759bb8f01b33e42bf912f3d479a886
    name: dinersclub
    type: application
    urls:
    - dinersclub-0.0.1.tgz
    version: 0.0.1
  dumper:
  - apiVersion: v2
    created: "2021-09-13T20:27:11.710326083+02:00"
    description: A Helm chart for Kubernetes
    digest: 3bb15876fb3918d843b83fb9b1dcbe4cbf1ae85e31d122ca4a8a19c6b46e106b
    name: dumper
    type: application
    urls:
    - dumper-0.0.1.tgz
    version: 0.0.1
  formcentral:
  - apiVersion: v2
    created: "2021-09-13T20:27:11.710732263+02:00"
    description: A Helm chart for Kubernetes
    digest: 2714ab498e2aa611f20d10dd515725b04e9b1be16a01258fe02b23efa7bb8eb2
    name: formcentral
    type: application
    urls:
    - formcentral-0.0.1.tgz
    version: 0.0.1
  linksniffer:
  - apiVersion: v2
    created: "2021-09-13T20:27:11.711117487+02:00"
    description: A Helm chart for Kubernetes
    digest: 937d5396dd86b6486c82b957f0af6dc64bcbd3ce1ff553bc8e8e18d73254d136
    name: linksniffer
    type: application
    urls:
    - linksniffer-0.0.1.tgz
    version: 0.0.1
  naughtybot:
  - apiVersion: v2
    created: "2021-09-13T20:27:11.711475777+02:00"
    description: A Helm chart for Kubernetes
    digest: 91e9933cf9a65359a2bfcff9f80628ff4ceae85d9fa86f56aad1c9e918e946f3
    name: naughtybot
    type: application
    urls:
    - naughtybot-0.0.1.tgz
    version: 0.0.1
  replybot:
  - apiVersion: v2
    created: "2021-09-13T20:27:11.711804313+02:00"
    description: A Helm chart for Kubernetes
    digest: 3022f7daf35e0ecbb8cfc09a61ac5292178eec01e0dc4220db74d90bab916caf
    name: replybot
    type: application
    urls:
    - replybot-0.0.1.tgz
    version: 0.0.1
  scratchbot:
  - apiVersion: v2
    created: "2021-09-13T20:27:11.712158638+02:00"
    description: A Helm chart for Kubernetes
    digest: 0c773b4d5d524d7731356d8957712ec7990d13086cb2826b596130e73283f7a0
    name: scratchbot
    type: application
    urls:
    - scratchbot-0.0.1.tgz
    version: 0.0.1
  scribble:
  - apiVersion: v2
    created: "2021-09-13T20:27:11.712763377+02:00"
    description: A Helm chart for Kubernetes
    digest: 47fa0bad4b7e0d0c04daa5f387b0d31894c32a48c8e6f0968e61ee3f3de99d48
    name: scribble
    type: application
    urls:
    - scribble-0.0.1.tgz
    version: 0.0.1
generated: "2021-09-13T20:27:11.707220818+02:00"
