apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: prometheus-kafka-offsets
  labels:
    heritage: Helm
    release: prometheus
  namespace: monitoring
spec:
  groups:
  - name: Kafka consumer group has high lag
    interval: 1m
    rules:
      - record: kafka:consumer_rate
        expr: max(rate(kafka_consumergroup_current_offset[5m])) by (consumergroup, topic)
      - record: kafka:consumer_lag
        expr: max(kafka_consumergroup_lag) by (consumergroup, topic)
      - record: kafka:consumer_lag_seconds
        expr: kafka:consumer_lag / kafka:consumer_rate
      - alert: KafkaConsumerGroupLagging
        expr: |
          kafka:consumer_lag > 10
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: |
            Kafka consumer lag...
          description: |
            Kafka consumer lag...
