apiVersion: batch/v1
kind: Job
metadata:
  name: gbv-state-debugger
  labels:
    app: gbv-state-debugger
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: gbv-state-debugger
        image: vlabresearch/replybot:0.0.62
        args:
        - node
        - lib/responses/debugger.js
        - "2672166766232015"
        resources:
          requests:
            cpu: "50m"
            memory: "100Mi"
        volumeMounts:
          - name: keys
            mountPath: /usr/src/app/keys
            readOnly: true
        envFrom:
        - secretRef:
            name: gbv-bot-envs
        env:
        - name: CHATBASE_BACKEND
          value: "@vlab-research/chatbase-postgres"
        - name: CHATBASE_DATABASE
          value: "chatroach"
        - name: CHATBASE_USER
          value: "chatroach"
        - name: CHATBASE_PASSWORD
          value: ""
        - name: CHATBASE_HOST
          value: "gbv-cockroachdb-public.default"
        - name: CHATBASE_PORT
          value: "26257"
        - name: BOTSPINE_KAFKA_BROKERS
          value: "gbv-kafka:9092"
        - name: BOTSPINE_MESSAGE_TOPIC
          value: "chat-events"
        - name: DASHBOARD_API
          value: "http://gbv-dashboard/api/v1"
        - name: FALLBACK_FORM
          value: "305"

      volumes:
        - name: keys
          secret:
            secretName: gbv-replybot-keys
