apiVersion: v1
kind: Pod
metadata:
  name: kafkaclient
  namespace: default
spec:
  containers:
  - name: kafka
    image: "confluentinc/cp-kafka:{{ .Values.kafka.imageTag }}"
    command:
      - sh
      - -c
      - "exec tail -f /dev/null"
